# Generated by Django 3.1.7 on 2021-07-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20210717_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='addhar',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
