# Generated by Django 3.1.7 on 2021-07-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_remove_person_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/css/img'),
        ),
    ]
